name: GitHub Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4  # Updated to the latest version

      # Step 2: Generate the snake animation manually using a script
      - name: Generate GitHub Contribution Snake
        run: |
          curl -o github-snake.svg "https://github.com/Platane/snk/raw/output/github-contribution-grid-snake.svg"

      # Step 3: Commit and Push Generated Files
      - name: Commit and Push Updates
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add github-snake.svg
          git commit -m "Updated GitHub Contribution Snake [skip ci]" || echo "No changes to commit"
          git push origin main
